permalink: /:categories/:year/:month/:title/
markdown: kramdown
highlighter: rouge
relative_permalinks: false
base_url: https://voxpelli.com
uid_base: http://voxpelli.com
push_hub: https://voxpelli.superfeedr.com/
author_name: Pelle Wessman
author_email: pelle@kodfabrik.se
blog_name: Pelle Wessman
paginate: 10
paginate_path: "/archive/full/:num/"
gems:
  - jekyll-paginate
